---
services: docker

install:
  - bundle install

script:
  # run kitchen tests (destroy, create, converge, setup, verify and destroy)
  - bundle exec kitchen test

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: BPWOyv/tklXbLuDTKPQu4rrX4fdIicLt1pjGyjfwb5C8J4zukn9UfCKCAiA++XZPuY91zlZY0/+486wcsECvurp+HIddr5qA57NR87bXb3pxHmg6vJXjxh+fvhjC1oqIhTRnbkZIs1wqWxX71s6R3geMbefMWUyk9BaFHXQT6aTrX/6MhJhH8ATkuHms7zoAnxvNYCVUgBTmwj4omOOn8C5mTy/ii4KM9M2g/r7JR2ReA3SZ9Dhradu4tWrpABRPRYeTvceCHx2hkBqEiOJsnE57HI3k/IZQbHiYO/PCpmqxk7XlklkAoYtr+FBQoQLbRobBk2fCH+VjOF2rsAu1EAhVUg6cevqnXpdqOo1183ypl3I6Et/j/JsO8upw9nJjsMJmmT4zgvoAAXaFaHVkrZPeKK2qO+3H5cYGwA9IOrggveUAvmLOYjkX8zyC1A4/RMTQNl5IgHFQWlZfEazmTCkFg5wGygP78/3pVQtGMzmE+j8dPG03B0TV5iVEaK8lPsgHmSJMCOeiu34P+9TYYXoUDt+IaaYqKnTV1uSxM0dl80OCo4KNT1Rfu0UtpJ5Zi7ehYs9Kk0Mym9Q5emLOgtwFBYnoiZWatrgX2JjoD7tlvR+pbYxR+bVeB+Q2fJyOLIiVT6LVJPO3PQUlM6l2ngsb0YFG72YpOyaEVLi7JnM=
